#!/bin/bash

USAGE="Usage: `basename $0` <infile> <outfilebasename>"

if [ "$#" -ne "2" ]; then
    echo "$USAGE"
    exit 1
fi

file=$1
out=$2

ffmpeg -i $file -acodec libvorbis -vcodec libtheora $out.ogv
ffmpeg -i $file -acodec libvorbis $out.webm
ffmpeg -i $file -acodec libfaac -ab 96k -vcodec libx264 -threads 0 $out.mp4
